name: Local JSON

on:
  workflow_dispatch:

jobs:
  local-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
        URL_BASE: ${{ vars.URL_BASE }}
        REDIS_URL: ${{ secrets.REDIS_URL }}

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar load json con reintento
        run: |
            MAX_RETRIES=5
            COUNT=0
            while [ $COUNT -lt $MAX_RETRIES ]; do
                if URL_BASE=${{ vars.URL_BASE }} REDIS_URL=${{ secrets.REDIS_URL }} node index.js --load-json; then
                    echo "✅ Comando ejecutado con éxito"
                    break
                else
                    echo "⚠️ Fallo en el intento $((COUNT+1)), reintentando en 5s..."
                    COUNT=$((COUNT+1))
                    sleep 5
                fi
            done
            if [ $COUNT -eq $MAX_RETRIES ]; then
                echo "❌ Error: Se alcanzó el máximo de reintentos"
                exit 1
            fi

      - name: Commit de cambios
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Actualización de db.json"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sacm1046/divisas.git

      - name: Finalizar procesos en segundo plano
        run: kill $(lsof -t -i:3000) || true
